language: node_js
node_js:
- 5.9.1
deploy:
  provider: npm
  email: ali@alicoding.com
  api_key:
    secure: Kxy+3yhmNSCtAD5HCVvk/WcII8ULI8QQ/UTdDnhvmLWMCGNAI53JxZ1QNP+n4S6ZynU+SFsu/zWqFVN6+moOhKn/9ZAo1Ia2WWrArgAVU5hT+NyJzyJOrq6hrVgCu4hHdYtiJIV8CJyZnyYqQK0WmXdLemxaPmG/GN6SYjv0Z5k=
  on:
    repo: alicoding/node-transifex
