language: node_js
node_js:
- 5.9.1

branches:
  only:
      - master # (PRs to master, master merges, master pushes)

env:
  global:
    - secure: "Kxy+3yhmNSCtAD5HCVvk/WcII8ULI8QQ/UTdDnhvmLWMCGNAI53JxZ1QNP+n4S6ZynU+SFsu/zWqFVN6+moOhKn/9ZAo1Ia2WWrArgAVU5hT+NyJzyJOrq6hrVgCu4hHdYtiJIV8CJyZnyYqQK0WmXdLemxaPmG/GN6SYjv0Z5k="

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG


