language: node_js
node_js:
- 8.9.3
branches:
  only:
  - master
env:
  global:
  - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: Kxy+3yhmNSCtAD5HCVvk/WcII8ULI8QQ/UTdDnhvmLWMCGNAI53JxZ1QNP+n4S6ZynU+SFsu/zWqFVN6+moOhKn/9ZAo1Ia2WWrArgAVU5hT+NyJzyJOrq6hrVgCu4hHdYtiJIV8CJyZnyYqQK0WmXdLemxaPmG/GN6SYjv0Z5k=
deploy:
  provider: npm
  email: ali@alicoding.com
  api_key:
    secure: dYznL6RTQQaauNKV+6wUIzoJBeIolUoUTGi5URvZ96x9+EM4mJSmCt8RCACC+5Y81T6KnWh5l6cv1MNuY2QyjtVJosoqYhNdPUB1ZfQauUI/vpNHJmnT0mN/ADSN8TjfCBfSq3TAubaAXefJ2ZsMbd344Bs0oCKrJ7C7TkBvaMs=
  on:
    tags: true
    branch: master
